CXXFLAGS=-std=c++11 -w -g -pipe -lstdc++
CC:=gcc

lib: include/lib
	cd include/lib && make all

IDLE: idle.cpp src/*
	$(CC) ./idle.cpp	 -o idle $(CXXFLAGS)
Xscript: script.cpp src/*
	$(CC) ./script.cpp	 -o script $(CXXFLAGS)

clean:
	rm -rf main.exe idle.exe idle main

all: IDLE Xscript lib

debug:all
	gdb ./script

run: all
	./idle
	