CC=g++	

IDLE: *.cpp src/*
	$(CC) ./idle.cpp	 -o idle	 -std=c++11 -w -g -ldl
Xscript: *.cpp src/*
	$(CC) ./script.cpp	 -o script	 -std=c++11 -w -g -ldl

clean:
	rm -rf main.exe idle.exe idle main

all: IDLE Xscript

debug:all
	gdb ./script

run: all
	./idle
	
