CXXFLAGS=-std=c++11 -w -g -pipe -ldl -lstdc++

lib: build/include/lib
	cd build/include/lib && make all

IDLE: idle.cpp src/*
	$(CC) ./idle.cpp	 -o build/idle $(CXXFLAGS)
Xscript: script.cpp src/*
	$(CC) ./script.cpp	 -o build/script $(CXXFLAGS)

clean:
	rm -rf build/main.exe build/idle.exe build/idle build/main
	rm -rf ./build/include/lib/stdlib ./build/include/lib/stdlib.exe 

all: IDLE Xscript lib

debug:all
	gdb ./script

run: all
	./idle
	
