CC=g++	

lib: include/lib
	cd include/lib && make all

IDLE: idle.cpp src/*
	$(CC) ./idle.cpp	 -o idle	 -std=c++11 -w -pipe -O2 -ldl -g
Xscript: script.cpp src/*
	$(CC) ./script.cpp	 -o script	 -std=c++11 -w -pipe -O2 -ldl -g

clean:
	rm -rf main.exe idle.exe idle main

all: IDLE Xscript lib

debug:all
	gdb ./script

run: all
	./idle
	
